name: hatzala_platform_models
description: Models for Hatzala Platform
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  lints: ^2.1.1
  test: ^1.24.6
